src/Entity/Promotion.php
<?php

namespace App\Entity;

use App\Repository\PromotionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PromotionRepository::class)
 */
class Promotion
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="integer")
     */
    private $formation_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $formateur_id;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getFormationId(): ?int
    {
        return $this->formation_id;
    }

    public function setFormationId(int $formation_id): self
    {
        $this->formation_id = $formation_id;

        return $this;
    }

    public function getFormateurId(): ?int
    {
        return $this->formateur_id;
    }

    public function setFormateurId(int $formateur_id): self
    {
        $this->formateur_id = $formateur_id;

        return $this;
    }
}

src/Form/PromotionType.php
<?php

namespace App\Form;

use App\Entity\Promotion;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PromotionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('formation_id')
            ->add('formateur_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Promotion::class,
        ]);
    }
}

src/Controller/PromotionController.php
<?php

namespace App\Controller;

use App\Entity\Promotion;
use App\Form\PromotionType;
use App\Repository\PromotionRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/promotion")
 */
class PromotionController extends AbstractController
{
    /**
     * @Route("/", name="app_promotion_index", methods={"GET"})
     */
    public function index(PromotionRepository $promotionRepository): Response
    {
        return $this->render('promotion/index.html.twig', [
            'promotions' => $promotionRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_promotion_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PromotionRepository $promotionRepository): Response
    {
        $promotion = new Promotion();
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotionRepository->add($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promotion/new.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_promotion_show", methods={"GET"})
     */
    public function show(Promotion $promotion): Response
    {
        return $this->render('promotion/show.html.twig', [
            'promotion' => $promotion,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_promotion_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        $form = $this->createForm(PromotionType::class, $promotion);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $promotionRepository->add($promotion, true);

            return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('promotion/edit.html.twig', [
            'promotion' => $promotion,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_promotion_delete", methods={"POST"})
     */
    public function delete(Request $request, Promotion $promotion, PromotionRepository $promotionRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$promotion->getId(), $request->request->get('_token'))) {
            $promotionRepository->remove($promotion, true);
        }

        return $this->redirectToRoute('app_promotion_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/promotion/_delete_form.html.twig
<form method="post" action="{{ path('app_promotion_delete', {'id': promotion.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ promotion.id) }}">
    <button class="btn">Delete</button>
</form>

templates/promotion/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/promotion/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Promotion{% endblock %}

{% block body %}
    <h1>Edit Promotion</h1>

    {{ include('promotion/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_promotion_index') }}">back to list</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}

templates/promotion/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion index{% endblock %}

{% block body %}
    <h1>Promotion index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Formation_id</th>
                <th>Formateur_id</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for promotion in promotions %}
            <tr>
                <td>{{ promotion.id }}</td>
                <td>{{ promotion.nom }}</td>
                <td>{{ promotion.formationId }}</td>
                <td>{{ promotion.formateurId }}</td>
                <td>
                    <a href="{{ path('app_promotion_show', {'id': promotion.id}) }}">show</a>
                    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_promotion_new') }}">Create new</a>
{% endblock %}

templates/promotion/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Promotion{% endblock %}

{% block body %}
    <h1>Create new Promotion</h1>

    {{ include('promotion/_form.html.twig') }}

    <a href="{{ path('app_promotion_index') }}">back to list</a>
{% endblock %}

templates/promotion/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Promotion{% endblock %}

{% block body %}
    <h1>Promotion</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ promotion.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ promotion.nom }}</td>
            </tr>
            <tr>
                <th>Formation_id</th>
                <td>{{ promotion.formationId }}</td>
            </tr>
            <tr>
                <th>Formateur_id</th>
                <td>{{ promotion.formateurId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_promotion_index') }}">back to list</a>

    <a href="{{ path('app_promotion_edit', {'id': promotion.id}) }}">edit</a>

    {{ include('promotion/_delete_form.html.twig') }}
{% endblock %}