src/Entity/OrganismeFormation.php
<?php

namespace App\Entity;

use App\Repository\OrganismeFormationRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=OrganismeFormationRepository::class)
 */
class OrganismeFormation
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $addresse;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $numero_telephone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email_contact;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getAddresse(): ?string
    {
        return $this->addresse;
    }

    public function setAddresse(string $addresse): self
    {
        $this->addresse = $addresse;

        return $this;
    }

    public function getNumeroTelephone(): ?string
    {
        return $this->numero_telephone;
    }

    public function setNumeroTelephone(string $numero_telephone): self
    {
        $this->numero_telephone = $numero_telephone;

        return $this;
    }

    public function getEmailContact(): ?string
    {
        return $this->email_contact;
    }

    public function setEmailContact(?string $email_contact): self
    {
        $this->email_contact = $email_contact;

        return $this;
    }
}

src/Form/OrganismeFormationType.php
<?php

namespace App\Form;

use App\Entity\OrganismeFormation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrganismeFormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom')
            ->add('addresse')
            ->add('numero_telephone')
            ->add('email_contact')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => OrganismeFormation::class,
        ]);
    }
}

src/Controller/OrganismeFormationController.php
<?php

namespace App\Controller;

use App\Entity\OrganismeFormation;
use App\Form\OrganismeFormationType;
use App\Repository\OrganismeFormationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/organisme/formation")
 */
class OrganismeFormationController extends AbstractController
{
    /**
     * @Route("/", name="app_organisme_formation_index", methods={"GET"})
     */
    public function index(OrganismeFormationRepository $organismeFormationRepository): Response
    {
        return $this->render('organisme_formation/index.html.twig', [
            'organisme_formations' => $organismeFormationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="app_organisme_formation_new", methods={"GET", "POST"})
     */
    public function new(Request $request, OrganismeFormationRepository $organismeFormationRepository): Response
    {
        $organismeFormation = new OrganismeFormation();
        $form = $this->createForm(OrganismeFormationType::class, $organismeFormation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $organismeFormationRepository->add($organismeFormation, true);

            return $this->redirectToRoute('app_organisme_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('organisme_formation/new.html.twig', [
            'organisme_formation' => $organismeFormation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_organisme_formation_show", methods={"GET"})
     */
    public function show(OrganismeFormation $organismeFormation): Response
    {
        return $this->render('organisme_formation/show.html.twig', [
            'organisme_formation' => $organismeFormation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_organisme_formation_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, OrganismeFormation $organismeFormation, OrganismeFormationRepository $organismeFormationRepository): Response
    {
        $form = $this->createForm(OrganismeFormationType::class, $organismeFormation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $organismeFormationRepository->add($organismeFormation, true);

            return $this->redirectToRoute('app_organisme_formation_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('organisme_formation/edit.html.twig', [
            'organisme_formation' => $organismeFormation,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_organisme_formation_delete", methods={"POST"})
     */
    public function delete(Request $request, OrganismeFormation $organismeFormation, OrganismeFormationRepository $organismeFormationRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$organismeFormation->getId(), $request->request->get('_token'))) {
            $organismeFormationRepository->remove($organismeFormation, true);
        }

        return $this->redirectToRoute('app_organisme_formation_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/organisme_formation/_delete_form.html.twig
<form method="post" action="{{ path('app_organisme_formation_delete', {'id': organisme_formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ organisme_formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/organisme_formation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/organisme_formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit OrganismeFormation{% endblock %}

{% block body %}
    <h1>Edit OrganismeFormation</h1>

    {{ include('organisme_formation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_organisme_formation_index') }}">back to list</a>

    {{ include('organisme_formation/_delete_form.html.twig') }}
{% endblock %}

templates/organisme_formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}OrganismeFormation index{% endblock %}

{% block body %}
    <h1>OrganismeFormation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom</th>
                <th>Addresse</th>
                <th>Numero_telephone</th>
                <th>Email_contact</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for organisme_formation in organisme_formations %}
            <tr>
                <td>{{ organisme_formation.id }}</td>
                <td>{{ organisme_formation.nom }}</td>
                <td>{{ organisme_formation.addresse }}</td>
                <td>{{ organisme_formation.numeroTelephone }}</td>
                <td>{{ organisme_formation.emailContact }}</td>
                <td>
                    <a href="{{ path('app_organisme_formation_show', {'id': organisme_formation.id}) }}">show</a>
                    <a href="{{ path('app_organisme_formation_edit', {'id': organisme_formation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_organisme_formation_new') }}">Create new</a>
{% endblock %}

templates/organisme_formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New OrganismeFormation{% endblock %}

{% block body %}
    <h1>Create new OrganismeFormation</h1>

    {{ include('organisme_formation/_form.html.twig') }}

    <a href="{{ path('app_organisme_formation_index') }}">back to list</a>
{% endblock %}

templates/organisme_formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}OrganismeFormation{% endblock %}

{% block body %}
    <h1>OrganismeFormation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ organisme_formation.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ organisme_formation.nom }}</td>
            </tr>
            <tr>
                <th>Addresse</th>
                <td>{{ organisme_formation.addresse }}</td>
            </tr>
            <tr>
                <th>Numero_telephone</th>
                <td>{{ organisme_formation.numeroTelephone }}</td>
            </tr>
            <tr>
                <th>Email_contact</th>
                <td>{{ organisme_formation.emailContact }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_organisme_formation_index') }}">back to list</a>

    <a href="{{ path('app_organisme_formation_edit', {'id': organisme_formation.id}) }}">edit</a>

    {{ include('organisme_formation/_delete_form.html.twig') }}
{% endblock %}